services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: ha-dev
    volumes:
      - ./ha-dev/config:/config
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/London
