homeassistant:
  name: Tado Dev
  latitude: 51.5
  longitude: -0.1
  elevation: 10
  unit_system: metric
  currency: GBP
  country: GB
  language: en
  time_zone: Europe/London

# Enable default frontend
frontend:
  themes: !include_dir_merge_named themes

# Lovelace dashboards
lovelace:
  resource_mode: yaml
  resources:
    - url: /local/tado-climate-card.js?v=33
      type: module
  dashboards:
    lovelace:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Tado Dev
      icon: mdi:view-dashboard
      show_in_sidebar: true

http:
recorder:

logger:
  default: warning
  logs:
    homeassistant.components.template: info

