title: Tado Dev
views:
  - title: Climate
    icon: mdi:thermostat
    cards:
      - type: custom:tado-climate-card
        entity: climate.hallway

      - type: custom:tado-climate-card
        entity: climate.living_room_2

      - type: custom:tado-climate-card
        entity: climate.front_bedroom

      - type: custom:tado-climate-card
        entity: climate.back_bedroom

      - type: custom:tado-climate-card
        entity: climate.rufus_bedroom

      - type: custom:tado-climate-card
        entity: climate.extension_dining

      - type: custom:tado-climate-card
        entity: climate.extension_patio

      - type: custom:tado-climate-card
        entity: climate.utility
